---
# Ansible playbook for an AWX server.
#
# @author Jeff Geerling.

- hosts: awx
  gather_facts: yes
  become: yes

  vars:
    awx_version: "devel"
    nodejs_version: "10.x"
    ansible_install_method: "pip"
    docker_install_compose: false
    docker_users:
      - vagrant
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.git
    - geerlingguy.pip
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.nodejs
    - geerlingguy.awx
