---
- hosts: xwings
  #vars:
  #    ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - update_os
    #- nginx
    - install_docker
