---
  #- name: Install docker
  #  shell: curl https://get.docker.com | sh

  - name: Install docker and some dependencies
    apt:
      name: python3-pip
      state: present

  - name: Install docker python module
    pip:
      name:
        - docker
        - docker-compose

  #- name: Modify privilege
  #  become: true
  #  shell: usermod -aG docker vagrant

  #- name: Set Artefact DOCKER.SOCK
  #  become: true
  #  shell: setfacl --modify user:vagrant:rw /var/run/docker.sock

  - name: Change privilege of docker
    become: true
    file: dest=/usr/bin/docker mode=+x

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Start docker service
    service:
      name: docker
      state: started


